import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import ScrollToTop from "@/components/ScrollTop";
import CreateProjectForm from "./projects/components/ProjectForm";
import { Suspense } from 'react'
import LoadingScreen from "@/components/LoadingScreen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trading-APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-xl w-full h-screen mx-auto relative overflow-y-auto px-1`}
      > 
        <ScrollToTop />
        <AuthProvider>
          <Suspense fallback={<div></div>}>
            <Navbar />
          </Suspense>
          <LoadingScreen />
          {children}
          <div className='sticky bottom-5 right-1'>
            <CreateProjectForm />
          </div>
        </AuthProvider>
        <Toaster position="top-right" richColors /> 
      </body>
    </html>
  );
}
